server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false     #表示是否将自己注册到Eureka Server，默认为true
    fetch-registry: false           #表示是否从Eureka Server获取注册的服务信息
  service-url:
    defaultZone: http://jiangzh:jiangzh123@localhost:8761/eureka/

#配置登录SpringSecurity的用户名和密码和权限。因为只要使用了SpringSecurity，就会交给它管理
spring:
  security:
    user:
      name: jiangzh
      password: jiangzh123
      roles: SUPERUSER

logging:
  config: classpath:logback.xml
