#因为需要网关zuul来控制，需要通过ribbon服务名的方式调用，所以user也需要引入Eureka的设置
server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://jiangzh:jiangzh123@localhost:8761/eureka/

mybatis-plus:
  mapper-locations: classpath*:com/mooc/meetingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mooc_meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: wangchao
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml

